config/routes.rb
ProjectGabriel::Application.routes.draw do

  root 'todo_list#index', as: 'todo_list', via: :all

  resources :task, except: [:show] do
    patch 'update_done', on: :member
  end

  resources :users

  get "todo_list/get_all_task", to: 'todo_list#get_all_task'
  get "todo_list/add_task/:id", to: 'todo_list#add_task', as: 'add_task'
  get "todo_list/order_by/:property", to: 'todo_list#order_by', as: 'order_by'

  controller :session do
    get 'login', to: :new
    post 'login', to: :create
    delete 'logout', to: :destroy
  end

  post 'session/authorize_user/.:format', to: 'session#authorize_user'

end

app/models/task.rb
class Task < ActiveRecord::Base
  belongs_to :todo_list

  validates_date :due_date, :on_or_after => lambda { Date.current }, message: 'Date should be in the future'
  validates :description, length: { maximum: 255}, presence: true, allow_blank: false
  validates :due_date, presence: true
  validates :priority, numericality: { greater_than_or_equal_to: 1, less_than_or_equal_to: 10}

  def self.due_date
    due_date.strftime("%m/%d/%y")
  end

end

app/models/todo_list.rb
class TodoList < ActiveRecord::Base
  has_many :tasks, dependent: :destroy
  belongs_to :user

  def empty_tasks
    tasks.destroy_all
  end

  def get_tasks_orderer_by task_property
    tasks.order task_property
  end

end

app/models/user.rb
class User < ActiveRecord::Base
  has_one :todo_list

  has_secure_password
  after_destroy :ensure_at_least_one_user

  validates :name, presence: true, uniqueness: true

  private

  def ensure_at_least_one_user
    if User.count.zero?
      raise "Can't delete last user"
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authorize

  protected

  def authorize
    unless User.find_by(id: session[:user_id])
      redirect_to login_url, notice: "Please Login."
    end
  end
end

app/controllers/session_controller.rb
class SessionController < ApplicationController
  skip_before_action :authorize

  def new
  end

  def create
    user = User.find_by(name: params[:name])
    if user and user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to todo_list_url
    else
      redirect_to login_url, notice: "Invalid user/password combination"
    end
  end

  def destroy
    session[:user_id] = nil
    session[:todo_list_id] = nil
    redirect_to login_url, notice: "Logged out"
  end

  def authorize_user
    @user = User.find_by(name: params[:user][:name])
    respond_to do |format|
      if @user
        session[:user_id] = @user.id
        format.json { render json: {id: @user.id}}
      else
        format.json { render json: { error_message: "Not valid user or password" }}
      end
    end
  end
end

app/controllers/task_controller.rb
class TaskController < ApplicationController
  before_action :set_task, only: [:edit, :update, :destroy, :update_done]

  def new
    @task = Task.new
  end

  def create
    @task = Task.new(task_params)
    respond_to do |format|
      if @task.save
        format.html { redirect_to add_task_url @task}
        format.json{ render json: {id: @task.id}, status: 200 }
      else
        render_wrong_formats format
      end
    end
  end

  def edit
  end

  def update
    respond_to do |format|
      if @task.update(task_params)
        format.html { redirect_to todo_list_url}
        format.json { render json: @task, status: 200}
      else
        render_wrong_formats format
      end
    end
  end

  def destroy
    @task.destroy
    redirect_to todo_list_url, notice: 'Task Removed'
  end

  def update_done
    @task.update_attribute(:done, params[:done])
    render nothing: true
  end

  private

  def render_wrong_formats format
    flash.now[:errors] =  @task.errors
    format.js { render 'task/new'}
    format.html { redirect_to action: :new }
    format.json { render json: @task.errors, status: :unprocessable_entity }
  end

  def set_task
    @task = Task.find(params[:id])
  end

  private

  def task_params
    params.require(:task).permit(:description, :done, :due_date, :priority)
  end

end

app/controllers/todo_list_controller.rb
class TodoListController < ApplicationController
  before_action :get_todo_list

  def index
    @tasks = @todo_list.tasks
  end

  def get_all_task
      render json: @todo_list.tasks.to_json, status: 200
  end

  def add_task
    @todo_list.tasks << Task.find(params[:id])
    @todo_list.tasks.reload
    redirect_to todo_list_url
  end

  def order_by
    @tasks = @todo_list.get_tasks_orderer_by(params[:property])
    render 'todo_list/index'
  end

  private

  def get_todo_list
    create_todo_list_if_none
    set_session_todo_list_id
    @todo_list = TodoList.find(session[:todo_list_id])
  end

  def set_session_todo_list_id
    session[:todo_list_id] ||= User.find(session[:user_id]).todo_list.id
  end

  def create_todo_list_if_none
    @user = User.find(session[:user_id])
    @user.todo_list = TodoList.create unless @user.todo_list
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :authorize, [:new, :create]

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    respond_to do |format|
      if @user.save
        format.html { redirect_to login_url, notice: 'User was successfully created.' }
      else
        format.html { render action: 'new' }
      end
    end
  end


  private

    def user_params
      params.require(:user).permit(:name, :password, :password_confirmation)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def page_title
    @title ||= 'Todo List'
  end
end

app/helpers/session_helper.rb
module SessionHelper
end

app/helpers/task_helper.rb
module TaskHelper

end

app/helpers/todo_list_helper.rb
module TodoListHelper
end

app/helpers/todo_rest_helper.rb
module TodoRestHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <div class="navbar-header navigationBar">
        <ul class="nav navbar-nav navbar-right">
          <% if @title and @title.downcase.include?('login') %>
            <li><%= link_to "Sign In", new_user_path %></li>
          <% elsif @title and @title.downcase.include?('sign') %>
            <li><%= link_to "Home", login_path %></li>
          <% else %>
            <li><%= link_to "Sign out", logout_path, method: :delete %></li>
          <% end %>
        </ul>
        <ul class="nav navbar-text navTitle" >
          <li><h3><%= page_title %></h3></li>
        </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ProjectGabriel</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<%= render 'layouts/header' %>

<%= yield %>

</body>
</html>

app/views/session/create.html.erb
<h1>Session#create</h1>
<p>Find me in app/views/session/create.html.erb</p>

app/views/session/destroy.html.erb
<h1>Session#destroy</h1>
<p>Find me in app/views/session/destroy.html.erb</p>

app/views/session/new.html.erb
<% @title="Please Login" %>
<div class="loginForm">
  <% if flash[:notice] %>
      <p class="alert alert-success notice"><%= flash[:notice] %></p>
  <% end %>
  <%= form_tag do %>
      <fieldset>
        <div class="loginDiv">
          <%= label_tag :name, 'Name:' %>
          <%= text_field_tag :name, params[:name] %>
        </div>
        <div class="loginDiv">
          <%= label_tag :password, 'Password:' %>
          <%= password_field_tag :password, params[:password] %>
        </div>
        <br>
        <div class="action marginTop70">
          <%= submit_tag "Login", class: 'btn btn-success' %>
        </div>
      </fieldset>
  <% end %>
</div>

app/views/shared/_error_notification.html.erb
<% if flash[:errors] %>
    <div class="alert alert-danger notice <%= addClass ? addClass : '' %> ">
      <% flash[:errors].full_messages.each do |msg| %>
          <p><%= msg %></p>
      <% end %>
    </div>
<% end %>

app/views/task/_add_task_button.html.erb
<%= button_to 'Add Task', new_task_path, method: :get, class: 'btn btn-success buttonAdd', remote: true %>

app/views/task/_edit_form.html.erb
<h3>Task </h3>
<%= form_for @task, url: task_path, method: :patch,remote: true do |f| %>
    <%= render 'task/form_inputs' , f: f %>
<% end %>

app/views/task/_form.html.erb
<h3>Task </h3>
<%= form_for @task, url: task_index_path, remote: true do |f| %>
    <%= render 'task/form_inputs' , f: f %>
<% end %>

app/views/task/_form_inputs.html.erb
<%= render 'shared/error_notification', addClass: 'marginLeft0' %>

<div>
  <%= label_tag :description %><br>
  <%= f.text_area :description, rows: 3, cols: 40, maxlength: 255 %>
</div>
<div>
  <%= f.label :priority %><br>
  <%= f.select :priority, options_for_select(1..10, @task.priority) %>

</div>
<div>
  <%= f.label :due_date %><br>
  <%= f.date_select :due_date, order: [:month, :day, :year] %>
</div>
<div>
  <%= f.submit 'Save', class: 'btn btn-success floatLeft marginTop20 saveButton' %>
  <%= link_to "<button type='button' class='btn btn-warning floatLeft marginTop20'>Cancel</button>".html_safe,
              todo_list_url, remote: true %>
</div>

app/views/task/create.html.erb
<h1>TaskController#create</h1>
<p>Find me in app/views/task_controller/create.html.erb</p>

app/views/task/destroy.html.erb
<h1>TaskController#destroy</h1>
<p>Find me in app/views/task_controller/destroy.html.erb</p>

app/views/task/edit.js.erb
$('#addingTaskDiv').html('<%= escape_javascript render 'task/edit_form'%>');

app/views/task/new.html.erb
<%= render 'task/form' %>

app/views/task/new.js.erb
$('#addingTaskDiv').html('<%= escape_javascript render 'task/form'%>');

app/views/todo_list/_table.html.erb
<% if notice %>
    <p id="tableNotice" class="alert alert-success notice"><%= notice %></p>
<% end %>

<table id="todoListTable" class="table">
  <thead>
    <tr>
      <th class="doneColumn">Completed</th>
      <th class="descriptionColumn">Description</th>
      <th class="priorityColumn"><%= link_to 'Priority', order_by_path(:priority), remote: true  %></th>
      <th class="dueDateColumn"><%= link_to 'Due Date', order_by_path(:due_date), remote: true  %></th>
      <th class="actionColumn">Action</th>
    </tr>
  </thead>
  <tbody>
  <% @tasks.each do |task| %>
      <tr>
        <td class="doneColumn">
            <%= check_box_tag task.id, 'done', task.done? %>
        </td>
        <td class="descriptionColumn"> <%= task.description %> </td>
        <td class="priorityColumn"> <%= task.priority %> </td>
        <td class="dueDateColumn"> <%= task.due_date.strftime("%m/%d/%Y") %> </td>
        <td class="actionColumn">
          <%= button_to 'Edit', edit_task_path(task), method: :get, class: 'btn btn-warning actionButton', remote: true %>
          <%= button_to 'Remove', task_path(task), method: :delete, class: 'btn btn-danger actionButton', remote: true %>
        </td>
      </tr>
  <% end %>
  </tbody>
  <script type="text/javascript">
      $(function() {
          setTimeout(function () {
              $('#tableNotice').hide();
          }, 7000);
      });

      $(":checkbox").click( function(data) {
          $.ajax({
              type: "PATCH",
              url: "/task/" + $(this).attr('name') + "/update_done",
              data: { done: $(this).is(':checked') }
          });
       });
  </script>
</table>

app/views/todo_list/add_task.html.erb
<h1>TodoList#add_task</h1>
<p>Find me in app/views/todo_list/add_task.html.erb</p>

app/views/todo_list/destroy.html.erb
<h1>TodoList#destroy</h1>
<p>Find me in app/views/todo_list/destroy.html.erb</p>

app/views/todo_list/edit.html.erb
<h1>TodoList#edit</h1>
<p>Find me in app/views/todo_list/edit.html.erb</p>

app/views/todo_list/index.html.erb
<div class="row">
  <div class="col-xs-6 col-md-8">
    <div id="todoListContainer">
      <%= render 'todo_list/table' %>
    </div>
  </div>
  <div class="col-xs-4 col-md-3">
    <div id="addingTaskDiv">
      <%= render 'task/add_task_button' %>
    </div>
  </div>
</div>

app/views/todo_list/index.js.erb
$('#todoListContainer').html('<%= escape_javascript render 'todo_list/table'%>');
$('#addingTaskDiv').html('<%= escape_javascript render 'task/add_task_button'%>');

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div class="alert alert-danger notice">
      <% @user.errors.full_messages.each do |msg| %>
        <p><%= msg %></p>
      <% end %>
    </div>
  <% end %>

  <div class="loginDiv">
    <%= f.label :name, 'Name:' %>
    <%= f.text_field :name %>
  </div>
  <div class="loginDiv">
    <%= f.label :password, 'Password:' %>
    <%= f.password_field :password %>
  </div>
  <div class="loginDiv">
    <%= f.label :password_confirmation, 'Password Confirmation:' %>
    <%= f.password_field :password_confirmation%>
  </div>
  <br>
  <div class="actions">
    <%= f.submit class: 'btn btn-success marginTop20' %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<h1>Listing users</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<% @title = "Sign in" %>
<div class="loginForm">
  <%= render 'form' %>
</div>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @user.name %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>